# Generated by Django 5.1.4 on 2024-12-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country_code', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('locality', models.CharField(max_length=100)),
                ('locality_verbose', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('cuisines', models.TextField()),
                ('avg_cost_for_two', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('has_table_booking', models.BooleanField()),
                ('has_online_delivery', models.BooleanField()),
                ('is_delivering', models.BooleanField()),
                ('price_range', models.IntegerField()),
                ('aggregate_rating', models.FloatField()),
                ('rating_color', models.CharField(max_length=20)),
                ('rating_text', models.CharField(max_length=20)),
                ('votes', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
